import { NextApiRequest, NextApiResponse } from 'next';

export default (req: NextApiRequest, res: NextApiResponse) => {
  res.status(200).json([
    {
      id: 1,
      slug: 'energy',
      title: 'Energy',
      subtitle: 'Global Energy Investment.',
      description: 'Metadata lorem ipsum sit amet. Donec ullamcorper nulla non metus auctor fringilla. Donec ullamcorper nulla non metus auctor fringilla. Vivamus sagittis lacus vel augue laoreet rutrum faucibus.',
      status: 'active',
      defaultSubgroup: 'energy-balance',
      subgroups: [
        { id: 1, name: 'Energy Balance', slug: 'energy-balance' },
        { id: 2, name: 'Energy Supply', slug: 'energy-supply' },
        { id: 3, name: 'Energy Efficiency', slug: 'energy-efficiency' },
        { id: 4, name: 'Energy Trade', slug: 'energy-trade' },
        { id: 5, name: 'Energy Investment', slug: 'energy-investment' },
        { id: 6, name: 'Electricity', slug: 'rlectricity' },
        { id: 7, name: 'Energy Price', slug: 'energy-price' },
        { id: 8, name: 'Energy Technology', slug: 'energy-technology' },
        { id: 9, name: 'Energy Consumption', slug: 'energy-consumption' },
        { id: 10, name: 'Internantional Comparison', slug: 'internantional-comparison' },
        { id: 11, name: 'Emissions & Natural Disaters', slug: 'emissions&natural-disaters' },
        { id: 12, name: 'Transporation sector', slug: 'transporation-sector' },
        { id: 13, name: 'Industry sector', slug: 'industry-sector' },
        { id: 14, name: 'Buildings', slug: 'buildings' },
        { id: 15, name: 'Energy Resources Reserves', slug: 'energy-esources-reserves' },
      ],
    },
    {
      id: 2,
      slug: 'socio-economic',
      title: 'Socio economic',
      subtitle: 'Agriculture.',
      description: 'Metadata lorem ipsum sit amet. Donec ullamcorper nulla non metus auctor fringilla. Donec ullamcorper nulla non metus auctor fringilla. Vivamus sagittis lacus vel augue laoreet rutrum faucibus.',
      defaultSubgroup: 'transportation',
      status: 'disabled',
      subgroups: [
        { id: 1, name: 'Transportation', slug: 'transportation' },
        { id: 2, name: 'Energy Supply', slug: 'energy-supply' },
        { id: 3, name: 'Energy Efficiency', slug: 'energy-efficiency' },
        { id: 4, name: 'Energy Trade', slug: 'energy-trade' },
        { id: 5, name: 'Energy Investment', slug: 'energy-investment' },
        { id: 6, name: 'Electricity', slug: 'rlectricity' },
        { id: 7, name: 'Energy Price', slug: 'energy-price' },
        { id: 8, name: 'Energy Technology', slug: 'energy-technology' },
        { id: 9, name: 'Energy Consumption', slug: 'energy-consumption' },
        { id: 10, name: 'Internantional Comparison', slug: 'internantional-comparison' },
        { id: 11, name: 'Emissions & Natural Disaters', slug: 'emissions&natural-disaters' },
        { id: 12, name: 'Transporation sector', slug: 'transporation-sector' },
        { id: 13, name: 'Industry sector', slug: 'industry-sector' },
        { id: 14, name: 'Buildings', slug: 'buildings' },
        { id: 15, name: 'Energy Resources Reserves', slug: 'energy-esources-reserves' },
      ],
    },
    {
      id: 3,
      slug: 'coal-power-plant',
      title: 'Coal power plants',
      subtitle: 'Capacity power plants in China.',
      description: 'Metadata lorem ipsum sit amet. Donec ullamcorper nulla non metus auctor fringilla. Donec ullamcorper nulla non metus auctor fringilla. Vivamus sagittis lacus vel augue laoreet rutrum faucibus.',
      defaultSubgroup: 'capacity',
      status: 'disabled',
      subgroups: [
        { id: 1, name: 'Capacity', slug: 'capacity' },
        { id: 2, name: 'Energy Supply', slug: 'energy-supply' },
        { id: 3, name: 'Energy Efficiency', slug: 'energy-efficiency' },
        { id: 4, name: 'Energy Trade', slug: 'energy-trade' },
        { id: 5, name: 'Energy Investment', slug: 'energy-investment' },
        { id: 6, name: 'Electricity', slug: 'rlectricity' },
        { id: 7, name: 'Energy Price', slug: 'energy-price' },
        { id: 8, name: 'Energy Technology', slug: 'energy-technology' },
        { id: 9, name: 'Energy Consumption', slug: 'energy-consumption' },
        { id: 10, name: 'Internantional Comparison', slug: 'internantional-comparison' },
        { id: 11, name: 'Emissions & Natural Disaters', slug: 'emissions&natural-disaters' },
        { id: 12, name: 'Transporation sector', slug: 'transporation-sector' },
        { id: 13, name: 'Industry sector', slug: 'industry-sector' },
        { id: 14, name: 'Buildings', slug: 'buildings' },
        { id: 15, name: 'Energy Resources Reserves', slug: 'energy-esources-reserves' },
      ],
    },
    {
      id: 4,
      slug: 'lorem ipsum',
      title: 'lorem ipsum',
      subtitle: 'lorem ipsum in China.',
      description: 'Metadata lorem ipsum sit amet. Donec ullamcorper nulla non metus auctor fringilla. Donec ullamcorper nulla non metus auctor fringilla. Vivamus sagittis lacus vel augue laoreet rutrum faucibus.',
      defaultSubgroup: 'energy-balance',
      status: 'disabled',
      subgroups: [
        { id: 1, name: 'Energy Balance', slug: 'energy-balance' },
        { id: 2, name: 'Energy Supply', slug: 'energy-supply' },
        { id: 3, name: 'Energy Efficiency', slug: 'energy-efficiency' },
        { id: 4, name: 'Energy Trade', slug: 'energy-trade' },
        { id: 5, name: 'Energy Investment', slug: 'energy-investment' },
        { id: 6, name: 'Electricity', slug: 'rlectricity' },
        { id: 7, name: 'Energy Price', slug: 'energy-price' },
        { id: 8, name: 'Energy Technology', slug: 'energy-technology' },
        { id: 9, name: 'Energy Consumption', slug: 'energy-consumption' },
        { id: 10, name: 'Internantional Comparison', slug: 'internantional-comparison' },
        { id: 11, name: 'Emissions & Natural Disaters', slug: 'emissions&natural-disaters' },
        { id: 12, name: 'Transporation sector', slug: 'transporation-sector' },
        { id: 13, name: 'Industry sector', slug: 'industry-sector' },
        { id: 14, name: 'Buildings', slug: 'buildings' },
        { id: 15, name: 'Energy Resources Reserves', slug: 'energy-esources-reserves' },
      ],
    },
    {
      id: 5,
      slug: 'lorem ipsum2',
      title: 'lorem ipsum',
      subtitle: 'lorem ipsum in China.',
      description: 'Metadata lorem ipsum sit amet. Donec ullamcorper nulla non metus auctor fringilla. Donec ullamcorper nulla non metus auctor fringilla. Vivamus sagittis lacus vel augue laoreet rutrum faucibus.',
      defaultSubgroup: 'energy-balance',
      status: 'disabled',
      subgroups: [
        { id: 1, name: 'Energy Balance', slug: 'energy-balance' },
        { id: 2, name: 'Energy Supply', slug: 'energy-supply' },
        { id: 3, name: 'Energy Efficiency', slug: 'energy-efficiency' },
        { id: 4, name: 'Energy Trade', slug: 'energy-trade' },
        { id: 5, name: 'Energy Investment', slug: 'energy-investment' },
        { id: 6, name: 'Electricity', slug: 'rlectricity' },
        { id: 7, name: 'Energy Price', slug: 'energy-price' },
        { id: 8, name: 'Energy Technology', slug: 'energy-technology' },
        { id: 9, name: 'Energy Consumption', slug: 'energy-consumption' },
        { id: 10, name: 'Internantional Comparison', slug: 'internantional-comparison' },
        { id: 11, name: 'Emissions & Natural Disaters', slug: 'emissions&natural-disaters' },
        { id: 12, name: 'Transporation sector', slug: 'transporation-sector' },
        { id: 13, name: 'Industry sector', slug: 'industry-sector' },
        { id: 14, name: 'Buildings', slug: 'buildings' },
        { id: 15, name: 'Energy Resources Reserves', slug: 'energy-esources-reserves' },
      ],
    }]);
};
