import { NextApiRequest, NextApiResponse } from 'next';

// export default (req: NextApiRequest, res: NextApiResponse) => {
//   res.status(200).json([
//     {
//       widget1: {
//         data: [
//           {
//             label: 'name1',
//             value: 'value1',
//           },
//           {
//             label: 'name2',
//             value: 'value3',
//           },
//         ],
//       },
//     },
//     {
//       widget2: {
//         data: [
//           {
//             label: 'name1',
//             value: 'value1',
//           },
//           {
//             label: 'name2',
//             value: 'value3',
//           },
//         ],
//       },
//     },
//   ]);
// };

export default (req: NextApiRequest, res: NextApiResponse) => {
  res.status(200).json([{
    indicator_en: 'Total Power of Agricultural Machinery',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Agriculture' },
    units_en: ['10 000 kw'],
    widget: ['line', 'choropleth', 'bar'],
    default: true,
    default_widget: 'choropleth',
  },
  {
    indicator_en: 'Farm Machinery',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Agriculture' },
    units_en: ['10 000 units'],
    widget: ['line', 'choropleth', 'bar', 'pie'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Irrigated Area of Cultivated Land',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Agriculture' },
    units_en: ['1 000 hectares'],
    widget: ['line', 'choropleth', 'bar'],
    default: false,
    default_widget: 'bar',
  },
  {
    indicator_en: 'Consumption of Chemical Fertilizers',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Agriculture' },
    units_en: ['10 000 tons'],
    widget: ['line', 'choropleth', 'bar', 'pie'],
    default: false,
    default_widget: 'bar',
  },
  {
    indicator_en: 'Irrigated Areas',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Agriculture' },
    units_en: ['Number'],
    widget: ['line', 'pie'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Effective Irrigated Area',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Agriculture' },
    units_en: ['Units'],
    widget: ['line', 'pie'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Number of Reservoirs',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Agriculture' },
    units_en: ['Units'],
    widget: ['line', 'pie'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Capacity of Reservoirs',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Agriculture' },
    units_en: ['Capacity of Reservoirs', '100m m3'],
    widget: ['line', 'pie'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Water-saving Irrigated Area ',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Agriculture' },
    units_en: ['10 000 hectares'],
    widget: ['line'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Area with Flood Prevention Measures',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Agriculture' },
    units_en: ['10 000 hectares'],
    widget: ['line'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Area with Soil Erosion under Control',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Agriculture' },
    units_en: ['10 000 hectares'],
    widget: ['line'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Total Length of Dikes',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Agriculture' },
    units_en: ['10 000 km'],
    widget: ['line'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Area of Land Protected by Dikes',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Agriculture' },
    units_en: ['10 000 hectares'],
    widget: ['line'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Building Floorspace',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Building' },
    units_en: ['10,000 sq.m'],
    widget: ['line', 'choropleth', 'bar', 'pie'],
    default: true,
    default_widget: 'line',
  },
  {
    indicator_en: 'Employment',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Employment' },
    units_en: ['10 000 persons', 'Percentage'],
    widget: ['line', 'pie'],
    default: true,
    default_widget: 'pie',
  },
  {
    indicator_en: 'Labour Force',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Employment' },
    units_en: ['10 000 persons'],
    widget: ['line'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Employed persons',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Employment' },
    units_en: ['10 000 persons'],
    widget: ['line'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Employed persons (Industry breakdown)',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Employment' },
    units_en: ['10 000 persons', 'Percentage'],
    widget: ['line', 'pie'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Employed persons (Urban/Rural breakdown)',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Employment' },
    units_en: ['10 000 persons'],
    widget: ['line', 'pie'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Unemployed persons in Urban areas',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Employment' },
    units_en: ['10 000 persons', 'Percentage'],
    widget: ['line'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Employed People in urban areas',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Employment' },
    units_en: ['10 000 persons'],
    widget: ['line', 'pie'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Exchange Rate',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Exchange Rate' },
    units_en: ['100 US Dollars', '100 Japanese Yen', '100 Hong Kong Dollars', '100 Euros'],
    widget: ['line', 'pie'],
    default: true,
    default_widget: 'pie',
  },
  {
    indicator_en: 'Gross National Income',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'GDP' },
    units_en: ['100 million yuan'],
    widget: ['line'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Gross Domestic Product',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'GDP' },
    units_en: ['100 million yuan', 'Percentage'],
    widget: ['line'],
    default: true,
    default_widget: 'line',
  },
  {
    indicator_en: 'Gross Domestic Product (Industry breakdown)',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'GDP' },
    units_en: ['100 million yuan', 'Percentage'],
    widget: ['line', 'pie'],
    default: false,
    default_widget: 'pie',
  },
  {
    indicator_en: 'Gross Domestic Product (Sector)',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'GDP' },
    units_en: ['100 million yuan', 'Percentage'],
    widget: ['line', 'pie'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Gross Domestic Product (constant price)',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'GDP' },
    units_en: ['100 million yuan', 'Percentage'],
    widget: ['line'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Gross Domestic Product (constant price) (Industry breakdown)',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'GDP' },
    units_en: ['100 million yuan', 'Percentage'],
    widget: ['line', 'pie'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Gross Domestic Product (constant price) (Sector)',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'GDP' },
    units_en: ['100 million yuan', 'Percentage'],
    widget: ['line', 'pie'],
    default: false,
    default_widget: 'pie',
  },
  {
    indicator_en: 'Gross National Income (constant price)',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'GDP' },
    units_en: ['Percentage'],
    widget: ['line'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Gross Domestic Product per capita (constant price)',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'GDP' },
    units_en: ['Percentage'],
    widget: ['line'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Gross National Income per capita (constant price)',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'GDP' },
    units_en: ['Percentage'],
    widget: ['line'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Gross National Income (compared to 1978)',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'GDP' },
    units_en: ['Percentage'],
    widget: ['line'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Gross Domestic Product (compared to 1978)',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'GDP' },
    units_en: ['Percentage'],
    widget: ['line'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Gross Domestic Product (compared to 1978) (Industry breakdown)',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'GDP' },
    units_en: ['Percentage'],
    widget: ['line', 'pie'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Gross Domestic Product (compared to 1978) (Sector)',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'GDP' },
    units_en: ['Percentage'],
    widget: ['line', 'pie'],
    default: false,
    default_widget: 'pie',
  },
  {
    indicator_en: 'Gross Domestic Product per capita (compared to 1978)',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'GDP' },
    units_en: ['Percentage'],
    widget: ['line'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Gross National Income per capita (compared to 1978)',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'GDP' },
    units_en: ['Percentage'],
    widget: ['line'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Gross Domestic Product (value-added)',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'GDP' },
    units_en: ['100 million yuan'],
    widget: ['line', 'pie'],
    default: false,
    default_widget: 'pie',
  },
  {
    indicator_en: 'Gross Domestic Product (main contributors to increase) (Industry breakdown)',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'GDP' },
    units_en: ['Percentage'],
    widget: ['line'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Gross Domestic Product (main contributors to increase) (Sector)',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'GDP' },
    units_en: ['Percentage'],
    widget: ['line'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Gross Domestic Product (main contributors to growth)',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'GDP' },
    units_en: ['Percentage'],
    widget: ['line'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Gross Domestic Product (main contributors to growth) (Industry breakdown)',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'GDP' },
    units_en: ['Percentage'],
    widget: ['line'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Gross Domestic Product (main contributors to growth) (Sector)',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'GDP' },
    units_en: ['Percentage'],
    widget: ['line'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Gross Regional Product',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'GDP' },
    units_en: ['100 million yuan'],
    widget: ['choropleth', 'bar'],
    default: false,
    default_widget: 'bar',
  },
  {
    indicator_en: 'Gross Regional Product (Industry breakdown)',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'GDP' },
    units_en: ['100 million yuan', 'Percentage'],
    widget: ['choropleth', 'bar', 'pie'],
    default: false,
    default_widget: 'choropleth',
  },
  {
    indicator_en: 'Gross Regional Product (Sector)',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'GDP' },
    units_en: ['100 million yuan'],
    widget: ['choropleth', 'bar', 'pie'],
    default: false,
    default_widget: 'pie',
  },
  {
    indicator_en: 'Per Capita Gross Regional Product',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'GDP' },
    units_en: ['100 million yuan'],
    widget: ['choropleth', 'bar'],
    default: false,
    default_widget: 'choropleth',
  },
  {
    indicator_en: 'Gross Regional Product (compared to preceding year)',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'GDP' },
    units_en: ['Percentage'],
    widget: ['choropleth', 'bar'],
    default: false,
    default_widget: 'choropleth',
  },
  {
    indicator_en: 'Gross Regional Product (compared to preceding year) (Industry breakdown)',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'GDP' },
    units_en: ['Percentage'],
    widget: ['choropleth', 'bar', 'pie'],
    default: false,
    default_widget: 'bar',
  },
  {
    indicator_en: 'Per Capita Gross Regional Product (compared to preceding year)',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'GDP' },
    units_en: ['Percentage'],
    widget: ['choropleth', 'bar'],
    default: false,
    default_widget: 'bar',
  },
  {
    indicator_en: 'Gross Domestic Product by Expenditure  Approach (100 million yuan)',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'GDP' },
    units_en: ['Percentage'],
    widget: ['line'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Final Consumption Expenditure',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'GDP' },
    units_en: ['Percentage'],
    widget: ['line'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Gross Capital Formation',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'GDP' },
    units_en: ['Percentage', '100 million yuan'],
    widget: ['line', 'pie'],
    default: false,
    default_widget: 'pie',
  },
  {
    indicator_en: 'Net Exports of Goods and Services',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'GDP' },
    units_en: ['Percentage'],
    widget: ['line'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Final Consumption Rate (%)',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'GDP' },
    units_en: ['Percentage'],
    widget: ['line'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Capital Formation Rate (%)',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'GDP' },
    units_en: ['Percentage'],
    widget: ['line'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Consumption Expenditure',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'GDP' },
    units_en: ['100 million yuan', 'Percentage'],
    widget: ['line', 'pie'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Trade of Goods and Services',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'GDP' },
    units_en: ['100 million yuan'],
    widget: ['line', 'pie'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Actual Final Consumption',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'GDP' },
    units_en: ['100 million yuan', 'Percentage'],
    widget: ['line', 'pie'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Consumption expenditure',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'GDP' },
    units_en: ['Yuan', 'Percentage'],
    widget: ['line', 'pie'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Consumption expenditure (compared to 1978)',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'GDP' },
    units_en: ['Percentage'],
    widget: ['line', 'pie'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Total Factor Productivity (Constant National Prices, 2011)',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'GDP' },
    units_en: [NaN],
    widget: ['line'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'International Trade of Goods',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Imports and exports' },
    units_en: ['100 million RMB', '100 million USD'],
    widget: ['line'],
    default: true,
    default_widget: 'line',
  },
  {
    indicator_en: 'Exports by SITC',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Imports and exports' },
    units_en: ['100 million RMB', '100 million USD'],
    widget: ['line', 'pie'],
    default: false,
    default_widget: 'pie',
  },
  {
    indicator_en: 'Imports by SITC',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Imports and exports' },
    units_en: ['100 million RMB', '100 million USD'],
    widget: ['line', 'pie'],
    default: false,
    default_widget: 'pie',
  },
  {
    indicator_en: 'International Trade (by region)',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Imports and exports' },
    units_en: ['100 million RMD', '100 million USD'],
    widget: ['pie'],
    default: false,
    default_widget: 'pie',
  },
  {
    indicator_en: 'Exported Commodities',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Imports and exports' },
    units_en: ['ton', NaN, '10 000 tons', '10 000 liters', 'Cotton Wool', 'barite', '10 000 m', '10 000 units', '10 000 sets', 'million units', 'including Sound Recording Apparatus', '10 000 RMB', '10 000 USD'],
    widget: ['pie'],
    default: false,
    default_widget: 'pie',
  },
  {
    indicator_en: 'Imported Commodities',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Imports and exports' },
    units_en: ['10 000 tons', NaN, 'ton', 'set', '10 000 sets', '10 000 units', 'unit', '10 000 RMB', '10 000 USD'],
    widget: ['pie'],
    default: false,
    default_widget: 'pie',
  },
  {
    indicator_en: 'Industrial Production',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Industry' },
    units_en: ['100 million tons', '10 000 tons', '100 million cu.m', '10 000 kiloliter', '100 million pieces', '100 million m', '10 000 tires', '10 000 weight cases', '10 000 kw', '10 000 units', '10 000 sets', 'unit', '10 000 lines', '100 million units', '100 million kwh'],
    widget: ['line', 'pie'],
    default: true,
    default_widget: 'pie',
  },
  {
    indicator_en: 'Disposable Income Per Capita',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Per capita income and consumption expenditure' },
    units_en: ['yuan', 'Percentage (compared to 1978)'],
    widget: ['line', 'pie'],
    default: true,
    default_widget: 'line',
  },
  {
    indicator_en: 'Disposable Income in Cash Per Capita',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Per capita income and consumption expenditure' },
    units_en: ['yuan'],
    widget: ['line', 'pie'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Consumption Expenditure Per Capita',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Per capita income and consumption expenditure' },
    units_en: ['yuan'],
    widget: ['line', 'pie'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Consumption Expenditure on Services  Per Capita',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Per capita income and consumption expenditure' },
    units_en: ['yuan'],
    widget: ['line', 'pie'],
    default: false,
    default_widget: 'pie',
  },
  {
    indicator_en: 'Consumption Expenditure in Cash Per Capita',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Per capita income and consumption expenditure' },
    units_en: ['yuan'],
    widget: ['line', 'pie'],
    default: false,
    default_widget: 'pie',
  },
  {
    indicator_en: 'Population',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Population' },
    units_en: ['10 000 persons'],
    widget: ['line', 'choropleth', 'bar'],
    default: true,
    default_widget: 'choropleth',
  },
  {
    indicator_en: 'Population (By Gender)',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Population' },
    units_en: ['10 000 persons', 'Percentage'],
    widget: ['line', 'pie'],
    default: false,
    default_widget: 'pie',
  },
  {
    indicator_en: 'Population (By Residence)',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Population' },
    units_en: ['10 000 persons', 'Percentage'],
    widget: ['line', 'pie'],
    default: false,
    default_widget: 'pie',
  },
  {
    indicator_en: 'Birth Rate',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Population' },
    units_en: ['‰'],
    widget: ['line'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Death Rate',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Population' },
    units_en: ['‰'],
    widget: ['line'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Natural Growth Rate',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Population' },
    units_en: ['‰'],
    widget: ['line'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Dependency Rate',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Population' },
    units_en: ['10 000 persons', 'Percentage'],
    widget: ['line', 'pie'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Dependency Ratio',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Population' },
    units_en: ['Percentage'],
    widget: ['line', 'pie'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Length of Railways in Operation',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Transportation' },
    units_en: ['10 000 km'],
    widget: ['line', 'pie'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Length of Highways',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Transportation' },
    units_en: ['10 000 km'],
    widget: ['line', 'pie'],
    default: false,
    default_widget: 'pie',
  },
  {
    indicator_en: 'Length of Navigable Inland Waterways',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Transportation' },
    units_en: ['10 000 km'],
    widget: ['line'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Length of Regular Civil Aviation Routes',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Transportation' },
    units_en: ['10 000 km'],
    widget: ['line', 'pie'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Length of Petroleum and Gas Pipelines',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Transportation' },
    units_en: ['10 000 km'],
    widget: ['line'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Passenger Traffic',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Transportation' },
    units_en: ['10 000 persons'],
    widget: ['line', 'pie'],
    default: true,
    default_widget: 'pie',
  },
  {
    indicator_en: 'Passenger Traffic per kilometer',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Transportation' },
    units_en: ['passengers per kilometer'],
    widget: ['line', 'pie'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Freight Traffic',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Transportation' },
    units_en: ['10 000 tons', '100 million tons per km'],
    widget: ['line', 'pie'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Travel Distance per passenger',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Transportation' },
    units_en: ['km'],
    widget: ['line', 'pie'],
    default: false,
    default_widget: 'pie',
  },
  {
    indicator_en: 'Average Freight Transport Distance',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Transportation' },
    units_en: ['km'],
    widget: ['line', 'pie'],
    default: false,
    default_widget: 'pie',
  },
  {
    indicator_en: 'Highspeed Railway in Operation',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Transportation' },
    units_en: ['Kilometers', 'Percentage'],
    widget: ['line'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Highspeed Passenger Traffic',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Transportation' },
    units_en: ['10 000 persons', 'Percentage', '100 million passenger/km'],
    widget: ['line'],
    default: false,
    default_widget: 'line',
  },
  {
    indicator_en: 'Civil Vehicles',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Transportation' },
    units_en: ['10 000 units'],
    widget: ['line', 'choropleth', 'bar', 'pie'],
    default: false,
    default_widget: 'bar',
  },
  {
    indicator_en: 'Motor Drivers',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Transportation' },
    units_en: ['10 000 persons'],
    widget: ['line', 'choropleth', 'bar', 'pie'],
    default: false,
    default_widget: 'choropleth',
  },
  {
    indicator_en: 'Private Vehicles',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Transportation' },
    units_en: ['10 000 units'],
    widget: ['line', 'choropleth', 'bar', 'pie'],
    default: false,
    default_widget: 'choropleth',
  },
  {
    indicator_en: 'Air Passenger Traffic',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Transportation' },
    units_en: ['10 000 persons', '10 000 persons/km'],
    widget: ['line', 'pie'],
    default: false,
    default_widget: 'pie',
  },
  {
    indicator_en: 'Air Freight Traffic',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Transportation' },
    units_en: ['tons', '10 000 ton/km'],
    widget: ['line', 'pie'],
    default: false,
    default_widget: 'pie',
  },
  {
    indicator_en: 'Total Air Traffic',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Transportation' },
    units_en: ['10 000 ton/km'],
    widget: ['line', 'pie'],
    default: false,
    default_widget: 'pie',
  },
  {
    indicator_en: 'Flying Time of General Aviation',
    classification: { group_en: 'Socioeconomic', subgroup_en: 'Transportation' },
    units_en: ['hr'],
    widget: ['line', 'pie'],
    default: false,
    default_widget: 'line',
  }]);
};
