name: Tests
on: [push]
jobs:
  cypress:
    runs-on: ubuntu-latest
    container: cypress/included:3.8.3
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 100

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '16.14.0'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Yarn cache
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: NextJS cache build
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}

      - name: Cypress tests
        uses: cypress-io/github-action@v2.2.7
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          build: yarn build
          start: yarn start
          wait-on: 'http://localhost:3000'
