name: Tests
on: [push]
jobs:
  cypress:
    name: Running client tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 100

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '16.14.0'

      - name: Cypress tests
        uses: cypress-io/github-action@v4
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
          NEXTAUTH_URL: http://localhost:3000
          NEXTAUTH_SECRET: nyanpony
        with:
          install-command: yarn install --immutable
          browser: chrome
          config-file: cypress.json
          command-prefix: yarn dlx
          command: yarn cy:run
          build: yarn build
          start: yarn start
          wait-on: 'http://localhost:3000'
